Коррекция форм, состояний элементов, добавление слайдера
htmlacademy-htmlcss/2086233-sedona-34 pull request #10
Opened 2022-06-29 12:50 UTC by Victoria273

Алёна, пыталась, но не получается пока 
- 1. Поколдовать с фоном на странице каталога, чтобы голубой цвет не выползал снизу background-image, апартаменты "выпали"
- 2. Иконки соц.сетей footer-social-item выделяются неровной областью и имеют авто width&height, хотя они заданы, не понимаю..
- 3. При наведении на range-input-end (стоимость "до") цифра сдвигается, также в этом блоке ползунки toggle не белого цвета, хотя его задала
- 4. В фильтрах не появляются галочка или круг по заданным псевдоэлементам для checked чекбоксов и радиокнопок.

Что мне нужно сделать, как можно скорректировать?
Спасибо большое!

2022-06-29 17:41 UTC, Safyann commented
1. для фоновой картинки  background-size: cover;
2. про фокус посмотри focus-visible
3. у .range-toggle background-color надо добавить для белого цвета ползунков и у .range-input-end border-left-width и border-width перезатирают друг друга, либо распиши все, либо оставь одно у hover можно их убрать они не меняются
4. :checked состояние должно быть у инпута, то есть .control-input[type="checkbox"]:checked + .control-mark-accomodation::after

2022-06-29 17:43 UTC, Safyann commented
и еще у страницы есть background и box-shadow

2022-06-29 17:45 UTC, Safyann commented
.need-to-visit нет паддинга сверху

2022-06-29 17:46 UTC, Safyann commented
нет декоративных треугольников на hero секции главной страницы, можно через affter добавить для .slogan

2022-07-01 03:40 UTC, Safyann requested changes

2022-07-01 03:40 UTC, Safyann commented on styles/styles.css
> +.control-input[type="checkbox"] + .control-mark-accomodation:checked::after {
:checked состояние должно быть у инпута, то есть .control-input[type="checkbox"]:checked + .control-mark-accomodation::after

2022-07-03 13:28 UTC, Victoria273 commented
Алёна, спасибо большое! Исправления внесла, продолжаю корректировать к защите - 
1. У .container {margin: 0 auto;} даёт 15,5px сбоку страницы, не придумала как убрать, чтобы в точности как макет.
2. В каталоге не ставятся галочки и точки в чекбоксы и радиокнопки, не удаётся их "выбрать";
также :focus-within выделяет подпункты вместе с текстом (нам нужно чтобы только квадратики и кружочки); 
 фокус с подпункта типа жилья "Гостиниц" переходит сразу на фильтр Стоимость (игнорируя подпункты "Мотель" и "Апартаменты"), и Апартаменты выпадают вниз, хотя ширина позволяет остаться в строке...
 3. Пагинация по пиксель-перфекту чуть не проходит, помимо моего margin-right: 8px, есть еще расстояние, но в коде элемента оно никак не обозначено..
 
 Очень переживаю, что у меня есть много ошибок, а я их не вижу, хочу всё сделать как нужно для защиты и отправить на первую проверку, подскажешь, пожалуйста, где мне нужны доработки?

2022-07-03 15:19 UTC, Safyann commented
@Victoria273 

1. у body сделай margin: 0 auto; width: 1200px; тогда как в макете будет
2. нет иконок в шапке

2022-07-03 19:54 UTC, Victoria273 commented
> @Victoria273
> 
> 1. у body сделай margin: 0 auto; width: 1200px; тогда как в макете будет
> 2. нет иконок в шапке

А ведь пробовала с body, поправила, спасибо! Иконки меняла на svg в разметку, чтобы отрисовать состояния.
![Снимок](https://user-images.githubusercontent.com/103250430/177055283-1a342394-6a41-4aa1-beea-941fdcf8f205.PNG)

2022-07-05 14:12 UTC, merged