Базовая стилизация
htmlacademy-htmlcss/2086233-sedona-34 pull request #5
Opened 2022-06-03 23:01 UTC by Victoria273

2022-06-04 17:50 UTC, Safyann requested changes

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  src: url("fonts/ptsans-400.woff2") format("woff2");
шрифты не подгружается, потому что путь не верный, сейчас в папке styles пытается найти fonts, но не может, надо выйти из папки и там искать fonts, то есть  ../fonts/

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  src: url("fonts/ptsans-700.woff2") format("woff2");
шрифты не подгружается, потому что путь не верный, сейчас в папке styles пытается найти fonts, но не может, надо выйти из папки и там искать fonts, то есть  ../fonts/

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
не обязательно везде указывать font-family, так как он наследуется из body

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  background-image: url("/images/search.svg");
лучше использовать относительные пути, то есть ../images

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  background-image: url("/images/favorite.svg");
лучше использовать относительные пути, то есть ../images

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  background-image: url("/images/index-background.jpg");
лучше использовать относительные пути, то есть ../images

2022-06-04 17:50 UTC, Safyann commented on styles/styles.css
> +  background-image: url("images/blurred-catalog-background.jpg");
не погрузится картинка, так как css пытается в папке styles найти images

2022-06-05 08:55 UTC, Victoria273 commented on styles/styles.css
> +  src: url("fonts/ptsans-400.woff2") format("woff2");
Пути ещё повторю, плохо укладывалось, исправила, спасибо, Алёна!

2022-06-05 08:57 UTC, Victoria273 commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
удалила, запомню, что ссылки значит не наследуют лишь color и text-decoration

2022-06-05 12:57 UTC, Safyann approved these changes

2022-06-05 12:57 UTC, merged