Сетка на флексах
htmlacademy-htmlcss/2086233-sedona-34 pull request #6
Opened 2022-06-08 13:25 UTC by Victoria273

2022-06-11 18:07 UTC, Safyann requested changes
1) подключи стили в html
2) все картинки должны иметь относительный путь, то есть начинаться ./ или ../
3) страница должна быть по центу, а не сбоку экрана, добавить container с margin: 0 auto

2022-06-11 20:06 UTC, Victoria273 commented
Алёна, спасибо!
> 1. подключи стили в html - здесь немного не пойму, стили вроде подключены <link rel="stylesheet" href="styles/styles.css">
> 2. все картинки должны иметь относительный путь, то есть начинаться ./ или ../ - исправила
> 3. страница должна быть по центу, а не сбоку экрана, добавить container с margin: 0 auto - поставила, но кажется не сработало...

2022-06-12 16:18 UTC, Safyann approved these changes
Принято, но в следующем коммите исправь подключение картинок в html файлах, так как они лежат на одном уровне с папкой images, то пути там должны начинаться с ./images и в .navigation-logo  margin: 0, 30px, -5px, 70px; без "," просто margin: 0 30px -5px 70px;

2022-06-12 16:18 UTC, Safyann commented on styles/styles.css
> +  margin: 0, 30px, -5px, 70px;
без "," просто margin: 0 30px -5px 70px;

2022-06-12 16:18 UTC, Safyann commented on styles/styles.css
> +также хотела спросить по visually-hidden - не скрываются такие надписи в браузере*/
visually-hidden дальше будет урок где добавишь

2022-06-12 16:19 UTC, merged